# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='name',
            new_name='title',
        ),
    ]
