# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0003_auto_20170819_0024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set([('user', 'calendar')]),
        ),
    ]
